package ru.skhool21.rubik.model;

public enum Formula {
    LEVEL2_UP_R,
    LEVEL2_UP_L,
    LEVEL2_DOWN_R,
    LEVEL2_DOWN_L,
    LEVEL2_LEFT_R,
    LEVEL2_LEFT_L,
    LEVEL2_RIGHT_R,
    LEVEL2_RIGHT_L,
    LEVEL3_CROSS1,
    LEVEL3_CROSS2,
    LEVEL3_CROSS3,
    LEVEL3_CROSS4,
    LEVEL3_CROSS_SORT1,
    LEVEL3_CROSS_SORT2,
    LEVEL3_CROSS_SORT3,
    LEVEL3_CROSS_SORT4,
    LEVEL3_ANGLE1,
    LEVEL3_ANGLE2,
    LEVEL3_ANGLE3,
    LEVEL3_ANGLE4,
    LEVEL3_ANGLE_SORT1,
    LEVEL3_ANGLE_SORT2,
    LEVEL3_ANGLE_SORT3,
    LEVEL3_ANGLE_SORT4;
}